// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C2_Final.Models;

public partial class Driver
{
    public int DriversLicenseNumber { get; set; }

    public string DriverLname { get; set; }

    public string DriverFname { get; set; }

    public string Ssn { get; set; }

    public virtual ICollection<Infraction> Infractions { get; set; } = new List<Infraction>();
}