// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C2_Final.Models;

public partial class Infraction
{
    public int InfractionsId { get; set; }

    public string InfractionsName { get; set; }

    public int DriversLicenseNumber { get; set; }

    public int LicensePlateNumber { get; set; }

    public virtual Driver DriversLicenseNumberNavigation { get; set; }

    public virtual Vehicle LicensePlateNumberNavigation { get; set; }
}