// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C2_Final.Models;

public partial class Login
{
    public int LoginId { get; set; }

    public string LoginUsername { get; set; }

    public string LoginPassword { get; set; }

    public string Role { get; set; }
}